#pragma once

#include "pch.h"

enum
{
	SUBSTANCE_AIMBOT_TAB_SUBTAB_RAGEBOT = 0,
	SUBSTANCE_AIMBOT_TAB_SUBTAB_ANTIAIM,
	SUBSTANCE_AIMBOT_TAB_SUBTAB_LEGIT,
	SUBSTANCE_AIMBOT_TAB_SUBTAB_TRIGGERBOT,

	SUBSTANCE_AIMBOT_TAB_ALL_SUBTABS,
};

enum
{
	SUBSTANCE_VISUALS_TAB_SUBTAB_ESP = 0,
	SUBSTANCE_VISUALS_TAB_SUBTAB_WORLD,
	SUBSTANCE_VISUALS_TAB_SUBTAB_GUI,

	SUBSTANCE_VISUALS_TAB_ALL_SUBTABS,
};


enum
{
	SUBSTANCE_AIMBOT_TAB = 0,
	SUBSTANCE_VISUALS_TAB,
	SUBSTANCE_WAYPOINTS_TAB,
	SUBSTANCE_MISC_TAB,
	SUBSTANCE_CONFIG_TAB,

	SUBSTANCE_TABS_COUNT
};

namespace Interface
{
	namespace Menu
	{
		extern std::vector<std::vector<int>>Tabs;
		extern bool Enabled;
		void Initialize();
		void Render();
	}
}