#pragma once

#include "pch.h"

enum
{
	SUBSTANCE_COMBAT_TAB_SUBTAB_LEGIT,
	SUBSTANCE_COMBAT_TAB_SUBTAB_TRIGGERBOT,
	SUBSTANCE_COMBAT_TAB_SUBTAB_RAGEBOT = 0,
	SUBSTANCE_COMBAT_TAB_SUBTAB_HACK_VERSUS_HACK,
	SUBSTANCE_COMBAT_TAB_SUBTAB_KREEDZ,

	SUBSTANCE_COMBAT_TAB_ALL_SUBTABS,
};

enum
{
	SUBSTANCE_VISUALS_TAB_SUBTAB_ESP = 0,
	SUBSTANCE_VISUALS_TAB_SUBTAB_WORLD,
	SUBSTANCE_VISUALS_TAB_SUBTAB_GUI,

	SUBSTANCE_VISUALS_TAB_ALL_SUBTABS,
};


enum
{
	SUBSTANCE_INFORMATION_TAB = 0,
	SUBSTANCE_COMBAT_TAB,
	SUBSTANCE_VISUALS_TAB,
	SUBSTANCE_MISC_TAB,
	SUBSTANCE_CONFIG_TAB,
	SUBSTANCE_SCRIPTS_TAB,

	SUBSTANCE_TABS_COUNT
};

namespace Interface
{
	namespace Menu
	{
		extern int NavigationMenu;
		extern bool Enabled;
		void Initialize();
		void Render();
	}
}